modLoader="javafml"
loaderVersion="[2,)"
license="CC0-1.0"
issueTrackerURL="https://github.com/xiader-45/Locator-Tweaks/issues"
displayURL="https://github.com/xiader-45/Locator-Tweaks"

[[mods]]
modId="locator_tweaks"
version="${version}"
displayName="Locator Tweaks"
logoFile="assets/locator-tweaks/icon.png"
authors="Xiader45"
description='''
Transforms Minecraft's locator bar into a survival navigation compass: waypoints, death & portal tracking, player heads, cardinal directions, and smart tooltips.
'''

[[mixins]]
config="locator-tweaks.mixins.json"

[[dependencies.locator_tweaks]]
modId="minecraft"
type="required"
versionRange="[26.3,27.0)"
ordering="NONE"
side="BOTH"

[[dependencies.locator_tweaks]]
modId="yet_another_config_lib_v3"
type="optional"
versionRange="[3.9.7,)"
ordering="NONE"
side="CLIENT"
