modLoader="javafml"
loaderVersion="[1,)"
license="CC0-1.0"

[[mods]]
modId="locator_tweaks"
version="${version}"
displayName="Locator Tweaks"
description='''Minimalist HUD locator tweaks for Minecraft - customize waypoint icons, colors, player heads, cardinal directions, and more.'''
logoFile="assets/locator-tweaks/icon.png"
authors="xiader-45"

[[mixins]]
config="locator-tweaks.mixins.json"

[[dependencies.locator_tweaks]]
modId="neoforge"
type="required"
versionRange="[26.1.2,)"
ordering="NONE"
side="CLIENT"

[[dependencies.locator_tweaks]]
modId="minecraft"
type="required"
versionRange="[26.1.2,26.2)"
ordering="NONE"
side="BOTH"

[[dependencies.locator_tweaks]]
modId="yet_another_config_lib_v3"
type="optional"
versionRange="[3.9.6,)"
ordering="NONE"
side="CLIENT"
