plugins {
    id "net.neoforged.moddev" version "2.0.147"
}

neoForge {
    version = "26.1.2.109"

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', 'locator_tweaks'
        }
        server {
            server()
            systemProperty 'neoforge.enabledGameTestNamespaces', 'locator_tweaks'
        }
    }

    mods {
        locator_tweaks {
            sourceSet project.sourceSets.main
        }
    }
}

base {
    archivesName = "locator-tweaks-neoforge-${project.minecraft_version}"
}

dependencies {
    compileOnly project(":common")
    compileOnly "dev.isxander:yet-another-config-lib:${project.yacl_version_neoforge}"
}

tasks.named('compileJava', JavaCompile) {
    source project(":common").sourceSets.main.allSource
}

tasks.named('processResources', ProcessResources) {
    from project(":common").sourceSets.main.resources
}
